Repository haifengl/smile, pull requests merged in 2018-05, with the labels that each got.

#308 addGitignore&RemoveOldMetadataFiles&AddSbtEclipseSupport
  .gitignore
  build.sbt
  core/.classpath
  core/.project
  data/.classpath
  data/.project
  demo/.classpath
  demo/.project
  graph/.classpath
  graph/.project
  interpolation/.classpath
  interpolation/.project
  math/.classpath
  math/.project
  nlp/.classpath
  nlp/.project
  plot/.classpath
  plot/.project
  project/plugins.sbt
Labels: new feature

#277 Add Binary K-Modes working with different binary disimilarity measure
  scala/src/main/scala/smile/clustering/k-modes/KModes.scala
  scala/src/main/scala/smile/clustering/k-modes/KModesModel.scala
  scala/src/main/scala/smile/math/distance/Binary/Hamming.scala
  scala/src/main/scala/smile/math/distance/Binary/MeanMahanttan.scala
  scala/src/main/scala/smile/math/distance/Binary/PatternDifference.scala
  scala/src/main/scala/smile/math/distance/Binary/ShapeDifference.scala
  scala/src/main/scala/smile/math/distance/Binary/SizeDifference.scala
  scala/src/main/scala/smile/math/distance/Binary/Vari.scala
  scala/src/main/scala/smile/math/distance/BinaryUtils.scala
  scala/src/main/scala/smile/validation/MutualInformationScore.scala
Labels: new feature

#312 add demo for Naive Bayes with Iris and add PolyaUrn model
  core/src/main/java/smile/classification/NaiveBayes.java
  demo/src/main/java/smile/demo/classification/ClassificationDemo.java
  demo/src/main/java/smile/demo/classification/NaiveBayesDemo.java
Labels: enhancement

#315 fix-update_readme_xstream_link
  README.md
Labels: document
